# @package _global_

defaults:
  - _self_

metadata:
  _target_: inference.examples.exponent.Numbers

processor:
  _target_: inference.examples.exponent.Exponent

num_threads: 1
gpus_per_thread: 1
batch_size: 1
num_workers: 1
info: False